# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
before_install: 
    - R -e 'source("https://install-github.me/r-lib/remotes")'
after_success:
    - Rscript -e 'covr::codecov()'
