---
title: "An introduction to sensemakr"
output: rmarkdown::html_vignette
author: Carlos Cinelli and Chad Hazlett
vignette: >
  %\VignetteIndexEntry{sensemakr}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Introduction

```{r, results = 'asis'}
library(sensemakr)

# loads dataset
data("darfur")

# runs regression model
model <- lm(peacefactor ~ directlyharmed + age + farmer_dar + herder_dar +
                         pastvoted + hhsize_darfur + female + village, data = darfur)

# runs sensemakr for sensitivity analysis
sensitivity <- sensemakr(model, treatment = "directlyharmed",
                               benchmark_covariates = "female",
                               kd = 1:3)
plot(sensitivity)
add_bound_to_contour(model, benchmark_covariates = "female", kd = 20, ky = 1)
add_bound_to_contour(model, treatment = "directlyharmed", benchmark_covariates = "female", kd = 20, ky = 1)

ovb_minimal_reporting(sensitivity, format = "html")
```

